# -*- coding: utf-8 -*-
"""Practica_EDE_Hiperestatica.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1zK0wWTpvqgiZc6VnGNwniARSLF4hWQnV

**EDE - Viga hiperestática**
"""

from sympy import SingularityFunction,symbols,Function,factorial,integrate
import matplotlib.pyplot as plt
import numpy as np
from sympy.plotting import plot
from sympy import init_printing
from sympy import *
from IPython.display import display, Math
from anastruct import Steel_profiles
import pandas as pd
import numpy as np
from anastruct import SystemElements

CM = 1.00

ss = SystemElements(mesh=200)

# Añadimos elementos
ss.add_element(location=[[0.0, 0.0], [1.0,0.0]])
ss.add_element(location=[[1.0, 0.0], [2.0,0.0]])

# Añadimos cargas
ss.point_load(2, Fx=0, Fy=-2.5*1000*CM)
ss.point_load(3, Fx=0, Fy=-5*1000*CM)
ss.q_load(element_id=1, q=2*1000*CM)
ss.q_load(element_id=2, q=2*1000*CM)

# Añadimos condiciones de borde
ss.add_support_fixed(node_id=1)
     

# Mostramos estructura generada
ss.show_structure()

# Resolvemos la estructura
ss.optimize(profile_type='IPE', fyd = 275/1.05, ELS = 2/200)

# Mostramos las reacciones
ss.show_reaction_force()

# Mostramos flectores
ss.show_bending_moment()


# Mostramos cortantes
ss.show_shear_force()

ss.show_displacement(factor = 10)

